# Python standard library
from os.path import join
from os import listdir
import os, sys

# 3rd party imports from pypi
from snakemake.workflow import workflow as wf_api
from snakemake.utils import R

# Local imports
from scripts.common import (
    allocated,
    provided, 
    references,
    str_bool
)

configfile: 'config.json'
exposure = config['options']['exposure']
outcome = config['options']['outcome']
workpath = config['project']['workpath']       # Pipeline's output directory
tmpdir = config['options']['tmp_dir']
threshold = 0.01

# Final ouput files of the pipeline
rule all:
    input:
        join(workpath, "mr", "res_single.csv")


# Import rules 
include: join("rules", "common.smk")
include: join("rules", "mr.smk")
